Multi-homing considerations
dotswg/dots-requirements pull request #61
Opened 2017-10-13 14:39 UTC by boucadair

2017-10-17 15:47 UTC, amortensen reviewed
I like the changes, but I'm not comfortable referring to an individual draft in this document now that it's on the verge of WGLC. I'd be comfortable referring to the architecture draft here, and then deciding what additional references the arch draft should contain.

2017-10-18 05:29 UTC, boucadair commented
Andrew,

I updated the text to remove the reference to the individual draft. Hope this is OK.

I will add an issue to track the point whether we need to cite that individual draft or not.

Thanks.

Cheers,
Med

De : amortensen [mailto:notifications@github.com]
Envoyé : mardi 17 octobre 2017 18:25
À : dotswg/dots-requirements
Cc : BOUCADAIR Mohamed IMT/OLN; Author
Objet : Re: [dotswg/dots-requirements] Multi-homing considerations (#61)


@amortensen commented on this pull request.

I like the changes, but I'm not comfortable referring to an individual draft in this document now that it's on the verge of WGLC. I'd be comfortable referring to the architecture draft here, and then deciding what additional references the arch draft should contain.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/dotswg/dots-requirements/pull/61#pullrequestreview-69933048>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AO8fV9QjIa7Co7WkiF1wDo_8I8gQJQjyks5stNTxgaJpZM4P4lpx>.

2017-10-27 17:59 UTC, amortensen requested changes

2017-10-27 17:59 UTC, amortensen commented on draft-ietf-dots-requirements.md
> +Multi-homed DOTS clients must maintain multiple DOTS associations with multiple upstream DOTS servers.
This seems out of place here. I was thinking of moving this and the other change to a new paragraph, and rewording to something like:
```A DOTS deployment may be multi-homed. DOTS clients in such deployments maintain associations with multiple DOTS servers. Multi-homed DOTS clients must be able to select ....```.

2017-10-30 21:34 UTC, merged