Fix nits in Section 1
dotswg/dots-requirements pull request #66
Opened 2017-10-23 11:47 UTC by boucadair

* clear some normative language in the terminology section
* remove some entries that are not used in the document
and some other minor edits.

2017-10-25 04:02 UTC, amortensen requested changes
Looks good. Two changes:

- Remove DOTS gateway from the list of possible DOTS agents.

- Expand SIP and keep RFC3261 in addition to the RFC7092.

2017-10-25 04:02 UTC, amortensen commented on draft-ietf-dots-requirements.md
> +  or data channel. It can be a DOTS client, DOTS server, or DOTS gateway.
A DOTS gateway itself is explicitly not a DOTS agent.

2017-10-25 04:02 UTC, amortensen commented on draft-ietf-dots-requirements.md
>    and a DOTS client, analogous to a SIP Back-to-Back User Agent (B2BUA)
SIP should probably be expanded to Session Initiation Protocol (SIP) here, and we should retain the reference to RFC3261.

2017-10-25 04:02 UTC, amortensen commented on draft-ietf-dots-requirements.md
> -Client signal:
The term `client signal` is used in the architecture draft, but it doesn't seem to be in any of the other drafts adopted by the WG. It seems like the requirements covering the ability to request mitigation and to receive feedback cover these definitions, so I'm comfortable removing them.

2017-10-25 06:01 UTC, boucadair commented
Is there any reason you want to exclude the gateway?


The definition of “dots gateway” says: “DOTS gateway:  ** A logical DOTS agent ** resulting from the logical…”

I can cite more text from the draft where it makes sense to “agent” denotes all the roles (client, server, gateway).

De : amortensen [mailto:notifications@github.com]
Envoyé : mercredi 25 octobre 2017 06:02
À : dotswg/dots-requirements
Cc : BOUCADAIR Mohamed IMT/OLN; Author
Objet : Re: [dotswg/dots-requirements] Fix nits in Section 1 (#66)


@amortensen requested changes on this pull request.

Looks good. Two changes:

·      Remove DOTS gateway from the list of possible DOTS agents.

·      Expand SIP and keep RFC3261 in addition to the RFC7092.

________________________________

In draft-ietf-dots-requirements.md<https://github.com/dotswg/dots-requirements/pull/66#discussion_r146749723>:

>

 DOTS agent:

 : Any DOTS-aware software module capable of participating in a DOTS signal

-  or data channel.

+  or data channel. It can be a DOTS client, DOTS server, or DOTS gateway.

A DOTS gateway itself is explicitly not a DOTS agent.

________________________________

In draft-ietf-dots-requirements.md<https://github.com/dotswg/dots-requirements/pull/66#discussion_r146749836>:

>

 DOTS gateway:

-: A logical DOTS agent resulting from the logical concatenation of a DOTS server

+: A DOTS-aware software module resulting from the logical concatenation of a DOTS server

   and a DOTS client, analogous to a SIP Back-to-Back User Agent (B2BUA)

SIP should probably be expanded to Session Initiation Protocol (SIP) here, and we should retain the reference to RFC3261.

________________________________

In draft-ietf-dots-requirements.md<https://github.com/dotswg/dots-requirements/pull/66#discussion_r146750345>:

> @@ -196,18 +196,6 @@ Heartbeat:

 : A message transmitted between DOTS agents over the signal channel, used as a

   keep-alive and to measure peer health.



-Client signal:

The term client signal is used in the architecture draft, but it doesn't seem to be in any of the other drafts adopted by the WG. It seems like the requirements covering the ability to request mitigation and to receive feedback cover these definitions, so I'm comfortable removing them.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/dotswg/dots-requirements/pull/66#pullrequestreview-71735975>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AO8fV-FKNRAYlwLH0czB6TnzKF82pGBCks5svrLTgaJpZM4QCtXR>.

2017-10-27 18:01 UTC, amortensen commented on draft-ietf-dots-requirements.md
> +  or data channel. It can be a DOTS client, DOTS server, or DOTS gateway.
Good point about the description of gateways. Maybe this? `... It can be a DOTS client, a DOTS server, or, as a logical DOTS agent, a DOTS gateway.`

2017-10-30 21:47 UTC, merged